<a href="https://colab.research.google.com/github/JasmineVan/LSTN/blob/main/51800128_LSTN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from tensorflow.keras import layers
from tensorflow.keras import models

In [ ]:
df = pd.read_csv("MovementAAL_RSS_1.csv")
data = np.array(df.values)
print(data.shape)
print(data[:3])

(27, 4)
[[-0.90476 -0.48     0.28571  0.3    ]
 [-0.57143 -0.32     0.14286  0.3    ]
 [-0.38095 -0.28    -0.14286  0.35   ]]


In [ ]:
X = data[:,:-1]
X = np.asarray(X.astype(np.float32))
y = data[:,-1]
print(X.shape)
print(y.shape)

(27, 3)
(27,)


In [ ]:
from collections import Counter
counter = Counter()
counter.update(y)
print(counter)

Counter({0.35: 5, 0.3: 3, -0.2: 3, 0.2: 3, 0.05: 2, 0.1: 2, -0.1: 2, 0.0: 1, -0.55: 1, 0.4: 1, 0.5: 1, 0.15: 1, -0.8: 1, -0.05: 1})


In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y = encoder.fit_transform(y)
print(y)

[10 10 11 11  2  5  9  2  1  6 12 11  2 11  6  7 13 10  8  0  3  9 11  9
  7  4  3]


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print('Train:')
print(X_train.shape)
print(y_train.shape)
print('Test:')
print(X_test.shape)
print(y_test.shape)

Train:
(18, 3)
(18,)
Test:
(9, 3)
(9,)


In [ ]:
print(X_train[:2])
print(X_train.shape[0])
print(X_train.shape[1])

[[ 0.       0.04     0.14286]
 [-0.57143 -0.32     0.14286]]
18
3


In [ ]:
from tensorflow.keras.utils import to_categorical
y_train = to_categorical(y_train)
print(y_train[:2])

[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]


In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras import layers , activations , models , preprocessing , utils
import tensorflow as tf
from  sklearn.model_selection import train_test_split

In [ ]:
print(X_train.shape[1])

3


In [ ]:
#embed_dim = 128
hidden_size = 20
batch_size = 32

timesteps = X_train.shape[1]
x_dim = 1

model = models.Sequential()
model.add(layers.LSTM(32, return_sequences=True,input_shape=(timesteps,x_dim)))
model.add(layers.SimpleRNN(hidden_size,input_shape=(timesteps,x_dim)))
model.add(layers.Dense(30,activation='sigmoid'))
model.add(layers.Dense(10,activation='softmax'))
model.add(layers.Dense(3,activation='tanh'))
model.compile(loss = 'categorical_crossentropy', optimizer='adam',metrics = ['accuracy'])
print(model.summary())

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_4 (LSTM)               (None, 3, 32)             4352      
                                                                 
 simple_rnn_7 (SimpleRNN)    (None, 20)                1060      
                                                                 
 dense_14 (Dense)            (None, 30)                630       
                                                                 
 dense_15 (Dense)            (None, 10)                310       
                                                                 
 dense_16 (Dense)            (None, 3)                 33        
                                                                 
Total params: 6,385
Trainable params: 6,385
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
#reshape 
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)
b = a.reshape(2,3,1)
print(b)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


In [ ]:
# chỉnh lại đầu vào 
print(X_train.shape)
n_examples = X_train.shape[0]
time_steps = X_train.shape[1] 
X_train_transformed = X_train.reshape(n_examples,time_steps,1)
print(X_train_transformed.shape)

(18, 3)
(18, 3, 1)


In [ ]:
X_test_transformed = X_test.reshape(len(X_test),time_steps,1)
y_pred = model.predict(X_test_transformed)
print(y_pred[:2])

[[ 0.02917281 -0.21007825  0.23657992]
 [ 0.02925212 -0.2103181   0.23672548]]


In [ ]:
y_pred = y_pred.argmax(axis=1)
print(y_pred)
print(y_test)

[2 2 2 2 2 2 2 2 2]
[ 1 11  6  9 10 11 13 10  2]


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00         1
           2       0.11      1.00      0.20         1
           6       0.00      0.00      0.00         1
           9       0.00      0.00      0.00         1
          10       0.00      0.00      0.00         2
          11       0.00      0.00      0.00         2
          13       0.00      0.00      0.00         1

    accuracy                           0.11         9
   macro avg       0.02      0.14      0.03         9
weighted avg       0.01      0.11      0.02         9



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
